[platformio]
default_envs = flight

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    sandeepmistry/LoRa @ ^0.8.0
    bblanchon/ArduinoJson @ ^7.2.0

[env:flight]
build_src_filter = +<flight/> -<ground/>
build_flags =
    -D IS_FLIGHT_COMPUTER
    -D CORE_DEBUG_LEVEL=0

[env:ground]
build_src_filter = +<ground/> -<flight/>
build_flags =
    -D IS_GROUND_STATION
    -D CORE_DEBUG_LEVEL=0
